version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data

volumes:
  cache:
    